events {
    worker_connections 1024;
}
http { 
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    limit_req_zone $binary_remote_addr zone=my_limit:10m rate=5r/s;
    server_tokens off;
    etag off;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }
    server {
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/self.crt;
        ssl_certificate_key /etc/nginx/certs/self.key;
        location /api/ {
            limit_req zone=my_limit burst=10 nodelay;

            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location / {
            proxy_pass http://frontend:80;
        }
    }
 }
